# BrAPIClient
#' The BrAPIClient class handles the configuration of the BrAPIClient connection and
#' is a wrapper class around httr2 functionality
#' @title BrAPIClient Class
#' @docType class
#' @description The BrAPIClient class handles the configuration of the BrAPI connection and
#' is a wrapper class around httr2 functionality
#'
#' @examples
#' BrAPIClient$new(token = "www.brapiserver.com", env="dev")
#' @export
BrAPIClient <- R6Class(
  "BrAPIClient",
  public = list(
                #' @description
                #' Creates a new instance of this [R6][R6::R6Class] class.
                #' It is not recommended that this object is created separately from the getBrAPI function
                #' @param server The BraPI server URL to be used
                #' @param authentication The authentication provider function string to be used if the server requires authentication
                #' @param verbosity The verbosity level to be used. See verbosity in httr2 package for details
                #'
    initialize = function(server = NULL,
                          authentication = NULL,
                          verbosity = NULL) {
      private$.server <- server
      private$.verbosity <- verbosity

      private$validate_authentication(authentication)
    },
    #' @description
    #' Generic get entity by id function to call the BrAPI server
    #' @param endpoint The endpoint to be called
    #'
    get = function(endpoint, id) {
        perform_request(this, paste0("//", id))
    }
  ),
  active = list(
    #' @field server
    #' Get or sets the server. In the case of setting it returns the BrAPIClient to allow for chaining.
    server = function(value) {
      if (missing(value)) {
        return(private$.server)
      } else {
        if (is.null(private$.server) || private$.server != value) {
            if (private$.verbose) {
                message(paste0("Changing server to ", value))
            }
          private$closeConnection()
          private$.server <- private$validate_server(value)
        }
        return(self)
      }
    },
    #' @field server
    #' Get or sets if dry_run. In the case of setting it returns the BrAPIClient to allow for chaining.
    dry_run = function(value) {
      if (missing(value)) {
        return(private$.dry_run)
      } else {
        if (is.null(private$.dry_run) || private$.dry_run != value) {
            if (private$.verbose) {
                message(paste0("Changing dry_run to ", value))
            }
         if (!is.logical(value)) {
            stop("dry_run must be TRUE or FALSE")
         }
         private$.dry_run <- value
        }
        return(self)
      }
    }
  ),
  private = list(
    .server = NULL,
    .authentication = NULL,
    .dry_run = TRUE,
    .verbosity = NULL,
    closeConnection = function() {
      # no op for now
    },
    guess_username = function() {
      # rstudio server
      username <- unname(Sys.getenv("LOGNAME"))

      # plain R
      if (username == "") {
        username <- unname(tolower(Sys.info()["user"]))
      }

      if (username == "" || username == "unknown")
        stop("Can't detect username automatically")

      return(username)
    },
    validate_authentication = function(authentication) {
      # TO test authentication
      return(authentication)
    }
  )
)

# Generated by Schema Tools Generator Version: '0.46.0-SNAPSHOT'
